src/main/java/com/infobalt/entities/Attachment.java
package com.infobalt.entities;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;

@Entity
public class Attachment implements Serializable{
	
	private static final long serialVersionUID = 8854090000228408077L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID")
	private Integer id;
	@ManyToOne
	private Task task;
	private String name;
	@Lob
	@Basic(fetch=FetchType.LAZY)
	@Column(length=10485760)
	private byte[] data;
	private String mimeType;
	private String description;
	
	public Attachment() {
		
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Task getTask() {
		return task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getData() {
		return data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMimeType() {
		return mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	};

	
	
}

src/main/java/com/infobalt/entities/Sprint.java
package com.infobalt.entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
public class Sprint implements Serializable{
	
	private static final long serialVersionUID = -7306567467554862764L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID")
	private Integer id;
	
	@ManyToOne
	private Project project;
	
	@NotNull
	@Size(min=2, max=32, message="Title must be between 2 and 32 characters.")
	private String title;
	
	private Date startDate;
	private Date finishDate;
	
	public boolean isActive(){
		Date date = new Date();
		if (date.after(startDate) && date.before(finishDate)){
			return true;
		}
		return false;
	}

	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	public Date getStartDate() {
		return startDate;
	}
	
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	
	public Date getFinishDate() {
		return finishDate;
	}
	
	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}
	
	public String getFormattedStartDate(){
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
		String date = sdf.format(startDate); 
		return date;
	}
	
	public String getFormattedFinishDate(){
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		String date = sdf.format(finishDate); 
		return date;
	}
}

src/main/java/com/infobalt/controllers/AttachmentController.java
package com.infobalt.controllers;

import java.io.ByteArrayInputStream;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.UploadedFile;

import com.infobalt.entities.Attachment;
import com.infobalt.models.AttachmentModel;
import com.infobalt.models.TaskModel;
import com.infobalt.models.UserModel;
import com.infobalt.services.AttachmentService;

public class AttachmentController {

	private static final Logger logger = LogManager.getLogger(UserController.class.getName());

	private AttachmentModel attachmentModel;
	private AttachmentService attachmentService;
	private TaskModel taskModel;
	private UserModel userModel;

	/**
	 * Method handles file upload event. It takes selected file and writes it into storage.
	 * @param event
	 */
	public void handleFileUpload(FileUploadEvent event) {
		Attachment attachment = new Attachment();
		attachment.setTask(taskModel.getCurrentTask());
		UploadedFile file = event.getFile();
		attachment.setName(file.getFileName());
		attachment.setData(file.getContents());
		attachment.setMimeType(file.getContentType());
		attachmentService.save(attachment);
		logger.info("User: " + "'" + userModel.getLoggedUser().showFullName() + "'" 
				+ " uploaded file: " + "'" + attachment.getName() + "'"
				+ " on task: " + "'" + taskModel.getCurrentTask().getId() + "'");
	}
	
	/**
	 * Method prepares the attachment for download. Based on given attachmentId it extracts the file from storage.
	 * @param attachmentId
	 */
	public void prepareDownloadFile(Integer attachmentId) {
		Attachment attachment = attachmentService.findById(attachmentId);
		ByteArrayInputStream stream = new ByteArrayInputStream(attachment.getData());
		String contentType = attachment.getMimeType();
		attachmentModel.setDownloadFile(new DefaultStreamedContent(stream, contentType, attachment.getName()));
	}

	public AttachmentModel getAttachmentModel() {
		return attachmentModel;
	}

	public void setAttachmentModel(AttachmentModel attachmentModel) {
		this.attachmentModel = attachmentModel;
	}

	public AttachmentService getAttachmentService() {
		return attachmentService;
	}

	public void setAttachmentService(AttachmentService attachmentService) {
		this.attachmentService = attachmentService;
	}

	public TaskModel getTaskModel() {
		return taskModel;
	}

	public void setTaskModel(TaskModel taskModel) {
		this.taskModel = taskModel;
	}

	public UserModel getUserModel() {
		return userModel;
	}

	public void setUserModel(UserModel userModel) {
		this.userModel = userModel;
	}

}

src/main/java/com/infobalt/controllers/TaskController.java
package com.infobalt.controllers;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.faces.application.ConfigurableNavigationHandler;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.primefaces.event.SelectEvent;

import com.infobalt.cached.CachedTask;
import com.infobalt.entities.Project;
import com.infobalt.entities.Sprint;
import com.infobalt.entities.Task;
import com.infobalt.entities.User;
import com.infobalt.enums.TaskStatus;
import com.infobalt.models.ProjectModel;
import com.infobalt.models.TaskModel;
import com.infobalt.models.UserModel;
import com.infobalt.services.TaskService;

public class TaskController {
	
	private static final Logger logger = LogManager.getLogger(UserController.class.getName());

	private TaskModel taskModel;
	private TaskService taskService;
	private ProjectModel projectModel;
	private UserModel userModel;
	private CachedTask cachedTask;
	
	public String create(){
		Task newTask = new Task();
		newTask.setCreator(userModel.getLoggedUser());
		newTask.setProject(projectModel.getCurrentProject());
		newTask.setCreationDate(new Date());
		newTask.setUpdateDate(new Date());
		newTask.setTaskStatus(TaskStatus.TODO);
		taskModel.setCurrentTask(newTask);
		return "addTask";
	}
	
	public String update(Task task){
		taskModel.setCurrentTask(task);
		return "task-update";
	}
	
	public String save(){
		taskService.save(taskModel.getCurrentTask());
		if(taskModel.getCurrentTask().getId() == null){
			logger.info("New task: " + "'" + taskModel.getCurrentTask().getTitle() + "'" + " was created by: " 
					+ "'" + userModel.getLoggedUser().showFullName() + "'");
		}
		else {
			logger.info("Task: " + "'" + taskModel.getCurrentTask().getTitle() + "'" + "was updated by: "
					+ "'" + userModel.getLoggedUser().showFullName() + "'");
		}
		return "saveTask";
	}
	
	public void save(Task task){
		taskService.save(task);
		cachedTask.reset();
	}
	
	public String cancel(){
		taskModel.setCurrentTask(null);
		return "cancel";
	}
	
	public void delete(Task task){
		taskService.delete(task);
	}
	
	public String overview(Task task){
		taskModel.setCurrentTask(task);
		return "overviewTask";
	}
	/**
	 * This method displays/renders UI component, if logged user is project worker, project manager or admin.
	 * @return returns true - if UI component is displayed
	 */
	public boolean displayItemToAuthorisedUser(){
		Project project = taskModel.getCurrentTask().getProject();
		List<User> users =  project.getUsers();
		User loggedUser = userModel.getLoggedUser();

		//display always to admin or project manager
		if(project.getProjectManager().getId() == loggedUser.getId() || loggedUser.getRole().getRole().equals("admin")){
			return true;
		}
		
		if(users != null && users.size() != 0){
			for(User u : users){
				if(u.getId().equals(loggedUser.getId())){
					return true;
				}
			}
		}
		
		return false;
	}
	/**
	 * This method displays project view page, if logged user is project worker, project manager, admin
	 * or logged user not participate in project workers, but have tasks with status DONE, assigned to him. 
	 * @return returns true - if page is displayed
	 */
	public boolean displayPage(){
		List<User> users = new ArrayList<User>();
		Project project = null;
		User loggedUser = null;
		Task currentTask = null;
		
		try {
			project = taskModel.getCurrentTask().getProject();
			users =  project.getUsers();
			loggedUser = userModel.getLoggedUser();
			currentTask = taskModel.getCurrentTask();
		
			//display always to admin or project manager
			if(project.getProjectManager().getId() == loggedUser.getId() || loggedUser.getRole().getRole().equals("admin")){
				return true;
			}
		
			if(users != null && users.size() != 0){
				for(User u : users){
					//Display page:
					//if logged user is assigned to task, and logged user not participate in project workers, and task status is DONE 
					if(loggedUser.getId().equals(currentTask.getAssignee().getId()) && !u.getId().equals(loggedUser.getId()) && currentTask.getTaskStatus() == TaskStatus.DONE ){
						return true;
					}else if(u.getId().equals(loggedUser.getId())){//if logged user participate in project workers
						return true;
					}
				}
			}	
		} catch (NullPointerException e) {
			return false;
		}
				
		return false;
	}
	
	public void removeSprint(Task task){
		taskService.removeSprint(task);
		cachedTask.reset();
	}
	
	/**
	 * Adds task to a sprint;
	 * sets AddedToSprintDate to current date;
	 * @param task - task to be added
	 * @param sprint - sprint to which task will be added
	 */
	public void addToSprint(Task task, Sprint sprint){
		taskService.addToSprint(task, sprint);
		cachedTask.reset();
	}
	
	/**
	 * Sets AddedToSprintDate to current date;
	 * Used when there is need to set sprint and date
	 * before saving task to a DB
	 */
	public void assignToSprintDate(){
		taskModel.getCurrentTask().setAddedToSprintDate(new Date());
	}
	
	public void changeStatus(){
		taskService.changeStatus(taskModel.getCurrentTask(), userModel.getLoggedUser());
	}
	
	public void changeStatus(Task task){
		taskService.changeStatus(task, userModel.getLoggedUser());
		cachedTask.reset();
	}
	
	public List<Task> findUserTasks(User user){
		return taskService.findUserTasks(user);
	}
	
	public List<Task> findAll() {
		return taskService.findAll();
	}
	
	public Task findById(Integer id){
		return taskService.findById(id);
	}
	
	public List<Task> findByProject(Project project){
		return taskService.findByProject(project);
	}	
	
	public List<Task> findBySprint(Sprint sprint){
		return taskService.findBySprint(sprint);
	}
	
	public List<Task> findByProjectAndStatus(Project project, TaskStatus taskStatus){
		return taskService.findByProjectAndStatus(project, taskStatus);
	}
	
	public List<Task> findBySprintAndStatus(Sprint sprint, TaskStatus taskStatus){
		return taskService.findBySprintAndStatus(sprint, taskStatus);
	}
	
	public List<Task> findNotInSprint(Project project){
		return taskService.findNotInSprint(project);
	}
	/**
	 * Finds tasks with status TODO and INPROGRESS, assigned to suspended users, who participates in project.
	 */
	public List<Task> findSuspendedUsersTasksInProject(Project project){
		return taskService.findSuspendedUsersTasksInProject(project);
	}
	
	private void saveResetedTask(Task task){
		taskService.save(task);
	}
	/**
	 * This method sets task status to TODO and assignee to NULL of selected tasks
	 * @return navigation query
	 */
	public String resetSuspendedTasks(){
		HttpServletRequest request = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
		
		if(request.getParameterValues("resetTask") != null){
			for(Object val : request.getParameterValues("resetTask")){
				Task task = findById(Integer.valueOf(val.toString()));
				task.setAssignee(null);
				task.setTaskStatus(TaskStatus.TODO);
				saveResetedTask(task);
			}
		}
		return "resetTasks";
	}
	
	public String getStatusStyle(TaskStatus status) {
		if (status == null) {
			return "";
		}
		String styleClass = "taskstatus-container ";
		if (status == TaskStatus.TODO) {
			styleClass += "taskstatus-todo";
		} else if (status == TaskStatus.DONE) {
			styleClass += "taskstatus-done";
		} else {
			styleClass += "taskstatus-inprogress";
		}
		return styleClass;
	}
	
	public String searchTasksByFragment(String fragment){
		taskModel.setFragment(fragment);
		return "taskSearch";
	}
	
	/**
	 * Handles select event on datatable row,
	 * navigates to selected item page
	 * @param event SelectEvent
	 */
	public void onRowSelect(SelectEvent event) {
		taskModel.setCurrentTask((Task) event.getObject());
		ConfigurableNavigationHandler handler = (ConfigurableNavigationHandler) FacesContext.getCurrentInstance()
				.getApplication().getNavigationHandler();
		handler.performNavigation("overviewTask");
	}
	
	/**
	 * Method is used to load task using its id saved in taskModel
	 * (navigation with GET parameters - from drag and drop dashboard)
	 * Redirected to home path if task do not exist.
	 */
	public void loadTask(){
		if (taskModel.getId() != null){
			int id = Integer.parseInt(taskModel.getId());
			Task task = findById(id);
			
			if (task != null) {
				taskModel.setCurrentTask(task);
				taskModel.setId(null);
			} else {
				ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		        try {
					ec.redirect(ec.getRequestContextPath() + "/");
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}			
	}
	
	public TaskModel getTaskModel() {
		return taskModel;
	}
	
	public void setTaskModel(TaskModel taskModel) {
		this.taskModel = taskModel;
	}
	
	public TaskService getTaskService() {
		return taskService;
	}
	
	public void setTaskService(TaskService taskService) {
		this.taskService = taskService;
	}

	public ProjectModel getProjectModel() {
		return projectModel;
	}

	public void setProjectModel(ProjectModel projectModel) {
		this.projectModel = projectModel;
	}

	public UserModel getUserModel() {
		return userModel;
	}

	public void setUserModel(UserModel userModel) {
		this.userModel = userModel;
	}

	public CachedTask getCachedTask() {
		return cachedTask;
	}

	public void setCachedTask(CachedTask cachedTask) {
		this.cachedTask = cachedTask;
	}

	public List<TaskStatus> getTaskStatuses() {
		return Arrays.asList(TaskStatus.values());
	}
	
}

src/main/webapp/user/project_tasks.xhtml
<ui:composition template="../templates/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jstl/core">

	<ui:define name="content">
		<h:outputScript library="js" name="sticky.js" target="head"/>
		<div id="stickyAnchor"></div>
		<div class="contentHeader smoothTransition stickyElement">
			<h:form>
				<p:commandLink value="#{projectModel.currentProject.title}" action="#{projectController.overview(projectModel.currentProject)}" />
				/
				<p:commandLink value="Tasks" action="allTasks" />
			</h:form>
			<h1>#{projectModel.currentProject.title}</h1>
		</div>
			
		<h:form id="projectView" styleClass="AfterStickyElement">
			<div class="contentBody" style="padding-top: 20px">
			<p:dataTable paginator="true" value="#{cachedTask.getProjectTasks(projectModel.currentProject)}"
				id="taskTable" widgetVar="taskTable" var="task" rows="10" 
				selectionMode="single" selection="#{task}" rowKey="#{task.id}"
				styleClass="ui-datatable-wrapped"
				paginatorTemplate="{FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}">
				<p:ajax event="rowSelect" listener="#{taskController.onRowSelect}" />
				<f:facet name="header">
        			<span style="width: 100%;">Project tasks</span>
        			<span style="position: absolute; right: 30px; padding-right: 1%;">
						<h:commandLink title="Export all project tasks.">
							<p:graphicImage name="img/csv.png" width="30" height="30" />
							<p:fileDownload value="#{projectController.getProjectTasksCsvFile()}" />
						</h:commandLink>
					</span>
				</f:facet>
    					
				<p:column headerText="Id" sortBy="#{task.id}" >
					<h:outputText value="#{task.id}"/>
				</p:column>

				<p:column headerText="Title" filterBy="#{task.title}" filterMatchMode="contains" sortBy="#{task.title}">
					<h:outputText value="#{task.title}"/>
				</p:column>
						
				<p:column headerText="Status" style="width:120px;" filterBy="#{task.taskStatus.value}" filterMatchMode="exact"  sortBy="#{task.taskStatus.value}">
					<f:facet name="filter">
						<p:selectOneMenu label="Select" onchange="PF('taskTable').filter()">
							<f:selectItem itemLabel="Select" itemValue="#{null}" noSelectionOption="true"/>
							<f:selectItems value="#{taskController.taskStatuses}" var="status" 
								itemValue="#{status.value}" itemLabel="#{status.value}"/>
						</p:selectOneMenu>
					</f:facet>
					<h:outputText value="#{task.taskStatus.value}"/>
				</p:column>
					
				<p:column headerText="Assignee"  sortBy="#{task.assignee.showFullName()}" filterBy="#{task.assignee.showFullName()}" filterMatchMode="contains">
					<h:outputText value="#{task.assignee.showFullName()}" styleClass="#{task.assignee.active ? '' : (userModel.getLoggedUser().id == task.project.projectManager.id ? (task.taskStatus.value != 'Done' ? 'statusSuspended' : '') : '')}"/>
				</p:column>
					
				<p:column headerText="Sprint" filterBy="#{task.sprint.title}" filterMatchMode="exact" sortBy="#{task.sprint.title}">
					<f:facet name="filter">
						<p:selectOneMenu onchange="PF('taskTable').filter()">
							<f:selectItem itemLabel="Select" itemValue="#{null}" noSelectionOption="true"/>
							<f:selectItems value="#{sprintController.findByProject(projectModel.currentProject)}"
								var="sprint" itemValue="#{sprint.title}" itemLabel="#{sprint.title}"/>
						</p:selectOneMenu>
					</f:facet>
					<h:outputText value="#{task.sprint.title}"/>
				</p:column>
						
				<p:column headerText="SP" style="width:45px;" sortBy="#{task.storyPoints}">
					<h:outputText value="#{task.storyPoints}"/>
				</p:column>
					
				<p:column headerText="Created" sortBy="#{task.creationDate}" sortMode="multiple"
					filterBy="#{task.creationDate}" filterFunction="#{dateFilterBean.filterByDate}">
					<f:facet name="filter">
    					<h:inputHidden id="filter"/>
  					</f:facet>
  					<f:facet name="header">
   						<p:outputLabel value="Created" />
    					<br />
    					<p:calendar id="from" pattern="yyyy-MM-dd"
    						onchange="$(PrimeFaces.escapeClientId('#{p:component('filter')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value"
    						onblur="PF('taskTable').filter()">
    						<p:ajax event="dateSelect" 
      						onstart="$(PrimeFaces.escapeClientId('#{p:component('filter')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value" 
      						oncomplete="PF('taskTable').filter()" />
    					</p:calendar>

    					<p:calendar id="to" pattern="yyyy-MM-dd"
    						onchange="$(PrimeFaces.escapeClientId('#{p:component('filter')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value"
    						onblur="PF('taskTable').filter()">
      						<p:ajax event="dateSelect" 
      						onstart="$(PrimeFaces.escapeClientId('#{p:component('filter')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value" 
      						oncomplete="PF('taskTable').filter()" />
    					</p:calendar>
  					</f:facet>
					<h:outputText value="#{task.creationDate}">
						<f:convertDateTime type="date" pattern="yyyy-MM-dd" />
					</h:outputText>
				</p:column>
						
				<p:column headerText="Updated" sortBy="#{task.updateDate}" sortMode="multiple" filterBy="#{task.updateDate}"
					filterFunction="#{dateFilterBean.filterByDate}">
					<f:facet name="filter">
						<h:inputHidden id="filter3" />
					</f:facet>
					<f:facet name="header">
						<p:outputLabel value="Updated" />
						<br />
						<p:calendar id="from3" pattern="yyyy-MM-dd"
							onchange="$(PrimeFaces.escapeClientId('#{p:component('filter3')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from3')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to3')}_input'))[0].value"
							onblur="PF('taskTable').filter()">
							<p:ajax event="dateSelect"
								onstart="$(PrimeFaces.escapeClientId('#{p:component('filter3')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from3')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to3')}_input'))[0].value"
								oncomplete="PF('taskTable').filter()" />
						</p:calendar>
						<p:calendar id="to3" pattern="yyyy-MM-dd"
							onchange="$(PrimeFaces.escapeClientId('#{p:component('filter3')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from3')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to3')}_input'))[0].value"
							onblur="PF('taskTable').filter()">
							<p:ajax event="dateSelect"
								onstart="$(PrimeFaces.escapeClientId('#{p:component('filter3')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from3')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to3')}_input'))[0].value"
								oncomplete="PF('taskTable').filter()" />
						</p:calendar>
					</f:facet>
					<h:outputText value="#{task.updateDate}">
						<f:convertDateTime pattern="yyyy-MM-dd" />
					</h:outputText>
				</p:column>
						
				<p:column headerText="Completed" sortBy="#{task.completeDate}" sortMode="multiple"
					filterBy="#{task.completeDate}" filterFunction="#{dateFilterBean.filterByDate}">
					<f:facet name="filter">
    					<h:inputHidden id="filter2" />
  					</f:facet>
  					<f:facet name="header">
   						<p:outputLabel value="Completed" />
    					<br />
    					<p:calendar id="from2" pattern="yyyy-MM-dd"
    						onchange="$(PrimeFaces.escapeClientId('#{p:component('filter2')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from2')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to2')}_input'))[0].value" 
      						onblur="PF('taskTable').filter()">
      						<p:ajax event="dateSelect" 
      						onstart="$(PrimeFaces.escapeClientId('#{p:component('filter2')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from2')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to2')}_input'))[0].value" 
      						oncomplete="PF('taskTable').filter()" />
    					</p:calendar>
    					<p:calendar id="to2" pattern="yyyy-MM-dd"
    						onchange="$(PrimeFaces.escapeClientId('#{p:component('filter2')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from2')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to2')}_input'))[0].value" 
      						onblur="PF('taskTable').filter()">
      						<p:ajax event="dateSelect" 
      						onstart="$(PrimeFaces.escapeClientId('#{p:component('filter2')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from2')}_input'))[0].value + ':' + $(PrimeFaces.escapeClientId('#{p:component('to2')}_input'))[0].value" 
      						oncomplete="PF('taskTable').filter()" />
    					</p:calendar>
  					</f:facet>
					<h:outputText value="#{task.completeDate}">
						<f:convertDateTime type="date" pattern="yyyy-MM-dd" />
					</h:outputText>
				</p:column>
				
				<f:facet name="footer"><span></span></f:facet>
						
				<p:ajax event="sort" oncomplete="PF('taskTable').unselectAllRows()"/>
				<p:ajax event="filter" oncomplete="PF('taskTable').unselectAllRows()"/>
						
			</p:dataTable>
			
			<h:panelGroup styleClass="search">
				<p:outputLabel for="searchDesc" value="Search by description:"/>
				<p:inputText id="searchDesc" placeholder="Enter fragment" binding="#{fragment}" />
				<p:commandButton value="Search" action="#{taskController.searchTasksByFragment(fragment.value)}"/>
			</h:panelGroup>
			<br/>
			<br/>
			</div>
		</h:form>
	</ui:define>
	
</ui:composition>